class AppStrings {
  static String appname = "Smile",
      bestDocApp = "Best Dentiste \n Appointment App",
      welcomeback = "Welcome Back!",
      weAreExited = "We're Excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password?",
      login = "login",
      category = "Cetagory",
      dentiste = "Dentiste Login",
      settings = "Settings",
      search = "Search Dentiste",
      signup = "Signup",
      welcome = "Welcome",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Dont Have an acoount?",
      endodontie = "Endodontie",
      generale = "Géneraliste",
      parodontie = "Parodontie",
      pediatrique = "Pédiatrique",
      chrirugie = "Chirurgie",
      esthetique = "Esthétique",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "Signnout";
}
