name: flutter_application_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  get: ^4.6.6
  http: ^1.2.1
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  fonts:
  - family: nunito
    fonts:
      - asset: assets/fonts/nunito.ttf
  - family: nunito_bold
    fonts:
      - asset: assets/fonts/nunito_bold.ttf

  assets:
  - assets/
  - assets/icons/
  - assets/images/

