// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHdSTIxJDeQWQR6kmSjv1AoVJHN9RcAw',
    appId: '1:380965168316:web:2775d74c6704109f16dcb9',
    messagingSenderId: '380965168316',
    projectId: 'smilev1-2ae7c',
    authDomain: 'smilev1-2ae7c.firebaseapp.com',
    storageBucket: 'smilev1-2ae7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ3So50JLsHvaU7vRfJjc5pIWl63oNkKk',
    appId: '1:380965168316:android:98d6db1a250a33e116dcb9',
    messagingSenderId: '380965168316',
    projectId: 'smilev1-2ae7c',
    storageBucket: 'smilev1-2ae7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-xMb_YgHIJ5vT8pv_0Pwe-w_eyK6acHw',
    appId: '1:380965168316:ios:cca43a753a472ae116dcb9',
    messagingSenderId: '380965168316',
    projectId: 'smilev1-2ae7c',
    storageBucket: 'smilev1-2ae7c.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-xMb_YgHIJ5vT8pv_0Pwe-w_eyK6acHw',
    appId: '1:380965168316:ios:cca43a753a472ae116dcb9',
    messagingSenderId: '380965168316',
    projectId: 'smilev1-2ae7c',
    storageBucket: 'smilev1-2ae7c.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRHdSTIxJDeQWQR6kmSjv1AoVJHN9RcAw',
    appId: '1:380965168316:web:2def944ba7f21de516dcb9',
    messagingSenderId: '380965168316',
    projectId: 'smilev1-2ae7c',
    authDomain: 'smilev1-2ae7c.firebaseapp.com',
    storageBucket: 'smilev1-2ae7c.appspot.com',
  );
}
